[package]
name = "pixelizer"
version = "0.1.0"
authors = ["IgorPerikov <perikov.igor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.4"
itertools = "0.9.0"
